### PR TITLE
Darkmode

### PR DESCRIPTION
**Pull request by Call-Me-G-Now**
Pull request for #24 

Draft because this will likely need rounds of tweaking. 
First thoughts?
I don't think I can catch ALL convertions, maybe it makes sence to just push it with the next build so  people can start ~~testing~~ :clown_face:  using it?

NOTE: This PR will be rebased and force-pushed to!

### CODE REVIEW

**Comment by cioraneanu** [comment]
Awesome! Will give you feedback tomorrow when I'll play with it.
No worries if it's not perfect these things always require several iterations.

**Comment by cioraneanu** [comment]
merged

Just checked out the darkmode branch. It looks like the white theme got a little too modified 😁 

If the current approach feels too fidly there is also the option to just start from the same commit again and create separate `dark-theme.css` file in which to only change what you don't like. That way that white theme remains untouched. 🤔

**Comment by Call-Me-G-Now** [comment]
aah yes, i see. I didn't check it very often. Most of the colors that have to change i changed to the nearest `--van--xxxx` var. I guess that's not going to cut it.

The problem remains that the colors are hardcoded. We can go either way:
- replace all hardcoded stuff with vars, populate light mode with current values, black mode with the dark
- got the `light.css` and `dark.css`

i think, at least for now, the latter is more convenient.

**Comment by cioraneanu** [comment]
> aah yes, i see. I didn't check it very often. Most of the colors that have to change i changed to the nearest `--van--xxxx` var. I guess that's not going to cut it.
> 
> The problem remains that the colors are hardcoded. We can go either way:
> 
> * replace all hardcoded stuff with vars, populate light mode with current values, black mode with the dark
> * got the `light.css` and `dark.css`
> 
> i think, at least for now, the latter is more convenient.

Sure let's go for latter :)

**Comment by Call-Me-G-Now** [comment]
This should be it. All condensed into variables.css.

lemme know what u think.

**Comment by cioraneanu** [comment]
- The code looks good, only thing I would change is move everything to a separate file like `dark.css`
- The UI is looks decent. The big parts are good, the small details are not yet there. Leaving a list of things that caught my eye:

```
**Transaction list page:**  
- text below description is way too muted making the contrast too big
- all icons are black
- there is a gray border at the bottom of each transaction

**Dashboard:**
- first card(Total balance) has some weird right borders which were not visible on white theme
- icons black(probably same problem as above)
- gray background color of graphs can be darker


**Add Transaction:**
- top tabs have white background
- tutorial button next to assistant needs color
- Big save button needs another color (this one is hard to pick since it's harded to achieve the look of the white theme. Maybe try an accent color like "#006064" 🤔 )

- The big + pink add bottom button needs a lighter pink 
```


Hope you don't take this personal, I've always been picky about UI 😇. You don't want to know the amount of hours I've put into tweaking the white theme. :)) 

I really appreciate your effort mate👍

**Comment by Call-Me-G-Now** [comment]
**Transaction list page:**  

- [ ] - text below description is way too muted making the contrast too big
- [ ] - all icons are black
- [ ] - there is a gray border at the bottom of each transaction

**Dashboard:**

- [ ] - first card(Total balance) has some weird right borders which were not visible on white theme
- [ ] - icons black(probably same problem as above)
- [ ] - gray background color of graphs can be darker


**Add Transaction:**

- [ ] - top tabs have white background
- [ ] - tutorial button next to assistant needs color
- [ ] - Big save button needs another color (this one is hard to pick since it's harded to achieve the look of the white theme. Maybe try an accent color like "#006064" 🤔 )

- [ ] - The big + pink add bottom button needs a lighter pink

**Comment by Call-Me-G-Now** [comment]
i think it's done. but i'm sure you'll find something new :laughing:

**Comment by cioraneanu** [comment]
It looks awesome!🎨 I really don't like torturing people with my picky UI goals😆 

Can you move the dark-theme overrides in a separate file like `dark.css` and make a Pull request into `dev` branch ? I'll like to play with it a little as well😇 


PS. The black icons I was reffering to earlier were the ones you choose for tags/categories. 😄

**Comment by Call-Me-G-Now** [comment]
> It looks awesome!🎨 I really don't like torturing people with my picky UI goals😆
> 
> Can you move the dark-theme overrides in a separate file like `dark.css` and make a Pull request into `dev` branch ? I'll like to play with it a little as well😇
> 
> PS. The black icons I was reffering to earlier were the ones you choose for tags/categories. 😄 

done! pls have a look

**Pull request merged**
