### PR TITLE
Strip Accents Settings

### PR DESCRIPTION
**Pull request by Marco77577**
We use Firefly III in German. Many words have accents and we like them to not be stripped. I took the liberty and changed the code to add corresponding settings and respect the settings wherever necessary.

Do you agree that is could be a feature required by people?

I did not test the code since I did not have the time to set up the environment. Could you sanity-check my code and  run it on your system to check if it works?

### CODE REVIEW

**Comment by cioraneanu** [comment]
Looks like a nice feature. Will investigate it👍

**Comment by cioraneanu** [comment]
Is this still necessary after the change to perserve what the user types in the assistant as a`description`? 😇

**Comment by Marco77577** [comment]
Not for the transactions. However, if you want this to be possible for tags, categories, and accounts, then yes.

**Comment by cioraneanu** [comment]
Some thoughts on this:
- 3 settings this feels overkill and crowds up the settings page. Creating one that applies to all 3 models is probably easier on the user
- no need to change anything in the `transaction-assistant.vue`
- apply the string manipulation inside the resource form component ([tag/id.vue](https://github.com/cioraneanu/firefly-pico/blob/main/front/pages/tags/%5B%5Bid%5D%5D.vue#L138)) and not in the transformer. This way the user can always see the actual result and not after he pressed the "save" button

**Comment by Marco77577** [comment]
I agree with the number of settings. I'll reduce it to a single one.

When you say "apply the string manipulation inside the resource form", do you mean in the `watch()` method? The `watch()` methods look like this at the moment:

```typescript
watch(tag, (newValue) => {
  if (!profileStore.lowerCaseTagName) {
    return
  }
  tag.value = newValue.toLowerCase()
})
```

It looks like strip accents is not applied here, but later in the transformer. So if I were to remove the logic from the transformers, the user would see the accents in the form, but the transformer would then not respect the strip accents setting and remove the accents. Do you agree or am I missing something?

**Comment by cioraneanu** [comment]
I've checked and for the `Tag` resource  the `removeAccents` is wrongfully applied the inside the transformer.
You can check out the`Category` resource; the transformer does not change the `name` field, only the watch is responsible for string manipulations.

**Comment by Marco77577** [comment]
Okay. I removed all `stripAccents()` calls from all transformers and moved them into the `watch()` methods of the templates. There is only one setting.

**Comment by cioraneanu** [comment]
Loook perfect! Just need to revert the changes inside `transaction-assistant.vue`.

**Comment by cioraneanu** [comment]
Merged with small tweaks via #87.

Thank you for your contribution 🥳

**Pull request closed without merging**
