### PR TITLE
Allow hiding accounts in dashboard

### LINKED ISSUE #17: [Suggestion] Allow hiding accounts on the main dashboard
If you have lots of accounts you may not really care about all of them all the time.
You could save some screen real estate if you allow marking some accounts as "hidden by default" so you would need to tap "See more" to show them. All totals would still include hidden accounts so it's purely a visual/extras change.

### PR DESCRIPTION
**Pull request by avee87**
Fixes #17 

Unfortunately, I couldn't test this properly because docker refuses to build the image for me. I don't fully understand the backend setup and frontend transformers so would appreciate some advice.

### CODE REVIEW

**Comment by cioraneanu** [comment]
No worries I'll take care of this feature.

Can you share your docker build error, maybe i can help?

I,ve posted a first draft for [contributions](https://github.com/cioraneanu/firefly-pico/blob/main/docs/contribute.md). It shows the commands to make the backend run locally.

**Comment by cioraneanu** [comment]
The frontend transformers are basically just 2 functions which convert backend API responses to something that your frontend is happy with. 

Think if you have a column of type date in your DB. The backend REST API will return that as a formatted string. But strings are not that useful for your frontend and you would rather have it as a date instance. 

**fromAPI** - will convert the string to date

**toAPI** - will convert the date back to a formatted string, in the format that your backend expects.

**Comment by avee87** [comment]
At first I was getting out-of-memory crashes when running `npm install`. After applying some fixes I ended up with this:
```
error: failed to solve: executor failed running [/bin/sh -c npm install     && npm run build     && tar --owner=www-data --group=www-data --exclude=.git -czf /tmp/app-front.tar.gz .]: exit code: 137
```

**Comment by avee87** [comment]
Speaking of which, when do you plan to release a new version? Some of the latest changes really improve usability of the app and it would be great to ship them.

**Comment by cioraneanu** [comment]
> At first I was getting out-of-memory crashes when running `npm install`. After applying some fixes I ended up with this:
> 
> ```
> 
> error: failed to solve: executor failed running [/bin/sh -c npm install     && npm run build     && tar --owner=www-data --group=www-data --exclude=.git -czf /tmp/app-front.tar.gz .]: exit code: 137
> 
> ```

This sounds like a out of memory issue [stackoverflow](https://stackoverflow.com/questions/59296801/docker-compose-exit-code-is-137-when-there-is-no-oom-exception)

**Comment by cioraneanu** [comment]
> Speaking of which, when do you plan to release a new version? Some of the latest changes really improve usability of the app and it would be great to ship them.

I'm planning on releasing everything under v1.1 when the dark theme is finished(#29) thanks to @Call-Me-G-Now. 

Will soon change the repository structure to create a `development` branch in which we can merge more freely and have separate frequent beta builds  from it.

**Comment by avee87** [comment]
Hmmm, I updated image to dev version and now getting this error:
```
Error: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "is_dashboard_visible" of relation "accounts" does not exist
LINE 1: update "accounts" set "is_dashboard_visible" = $1, "updated_...
                              ^ (Connection: pgsql, SQL: update "accounts" set "is_dashboard_visible" = 1, "updated_at" = 2024-05-15 18:48:54 where "id" = 53)
```
Aren't database migrations supposed to run automatically?

**Comment by avee87** [comment]
Also, not sure if related, but all accounts show up like this even though they are visible on dashboard:
Screenshot 2024-05-15 at 19 50 09

**Comment by cioraneanu** [comment]
> Hmmm, I updated image to dev version and now getting this error:
> 
> ```
> Error: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "is_dashboard_visible" of relation "accounts" does not exist
> LINE 1: update "accounts" set "is_dashboard_visible" = $1, "updated_...
>                               ^ (Connection: pgsql, SQL: update "accounts" set "is_dashboard_visible" = 1, "updated_at" = 2024-05-15 18:48:54 where "id" = 53)
> ```
> 
> Aren't database migrations supposed to run automatically?

Yes it migrated automatically on my end. Try recreating the container to see if it was a 1 time hiccup. Alternatively run: `php artisan migrate` manually.

**Comment by cioraneanu** [comment]
> Also, not sure if related, but all accounts show up like this even though they are visible on dashboard: Screenshot 2024-05-15 at 19 50 09

Looks normal if you dont have that coulmn in your DB yet...

**Comment by avee87** [comment]
After a couple of restarts it still hasn't migrated.

Looks I'm not the only one experiencing issues with auto-migrations: #35
I can run the migration manually but it's not great if significant number of users get a broken install after the next release so let's figure out why it may not be running...

**Comment by avee87** [comment]
Checkmark is missing even after database migration! I suspect that it may be due to default only applying to newly created rows rather than existing ones.
Also, no matter what I do I can't actually make accounts hidden - all are shown regardless of settings.

**Pull request closed without merging**
